### ISSUE TITLE
Async reindex collidates with reindexing from Observers

### ISSUE THREAD

**Issue by tomtone** [magento-hackathon/AsyncIndex#17]
While running the async module indexes are rebuilt from cron. But e.g. sales_model_service_quote_submit_success Event forces the CatalogInventory to reindex Data as well. This colidates from time to time (depending on the amount of sales and interval for async indexing). 

Magento Version where this Bug occurs: 1.9.0.1

Any suggestions ?

**Comment by phrench** [comment]
What happens exactly to a sale when a collision happens?
Is this a serious issue?

**Comment by Silarn** [comment]
This doesn't just happen with Update on Save selected?

**Comment by WinstonN** [comment]
I do multiple orders a second in my 1.8.1.0 CE store. I have my indexes running every 5 minutes, with 100 events in each run. I also commented out, via a rewrite, the Mage::getResourceSingleton('catalog/product_indexer_price')->reindexProductIds($productIds); call that get's called after each order in Mage_CatalogInventory_Model_Observer::reindexQuoteInventory()

Under System -> Config -> System -> Asynchronous Indexing -> Enable Partial Automatic Indexing = Yes

I never get any deadlocks now. My peaks were 9 orders a second with this configuration

**Comment by Flyingmana** [comment]
It may be worth to mention this in the readme with possible downsides
