### ISSUE TITLE
Compatibility to Magento 1.9.2.2 / SUPEE-6788

### ISSUE THREAD

**Issue by avstudnitz** [magento-hackathon/AsyncIndex#20]
Admin URL has to be changed, see https://info2.magento.com/rs/318-XBX-392/images/SUPEE-6788-Technical%20Details.pdf.

**Comment by clijunky** [comment]
Waiting anxiously on this.  It's the last piece of the SUPEE-6788 puzzle for me.  Post SUPEE-6788 error:
`$ php hackathon_async_index.php`
`Starting Index - Process (all, only required Parts)`
`PHP Fatal error:  Call to a member function executePartialIndex() on a non-object in /path/to/magento/public_html/shell/hackathon_async_index.php on line 36`
